version: '3.8'

services:
  # Servicio de Apache con PHP
  webserver:
    image: php:apache
    container_name: my-apache-php-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  # Servicio de MySQL (o MariaDB)
  database:
    image: mariadb
    container_name: my-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
